name: NickWorkflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python Nick.py

      - name: This is Naman
        run: echo Hello, Naman. This is Ubuntu.


  job2:
      runs-on: windows-latest

      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-python@v4
          with:
            python-version: '3.10' 
        - run: python Nick.py

        - name: This is Naman
          run: echo Hello, Naman. This is Windows.
